///////////////////////////////////////////////////////////
//  Location.cs
//  Implementation of the Class Location
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Text;

namespace Mazegame.Entity
{
    public class Location
    {
        private Hashtable characters;
        private Inventory items;

        private String description;
        private String label;
        private readonly ExitCollection exitCollection;

        public Location()
        {
            exitCollection = new ExitCollection();
            items = new Inventory();
        }

        public Location(String description, String label) : this()
        {
            Description = description;
            Label = label;
        }

        public Inventory GetInventory()
        {
            return items;
        }

        public String Description
        {
            get { return description; }
            set { description = value; }
        }

        public String Label
        {
            get { return label; }
            set { label = value; }
        }

        public ExitCollection GetExitCollection()
        {
            return exitCollection;
        }

        public override string ToString()
        {
            return
                "**********\n" + this.Label + "\n**********\n"
                + "Exits found :: " + exitCollection.AvailableExits()
                + "\n" + items.ToString() 
                + "\n**********\n" + this.Description + "\n**********\n";
        }
    } 
} 