///////////////////////////////////////////////////////////
//  NonPlayerCharacter.cs
//  Implementation of the Class NonPlayerCharacter
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;
using System.Collections;

namespace Mazegame.Entity
{
    public class NonPlayerCharacter : Character
    {
        private Boolean hostile;
        private String dialogue;
        

        public NonPlayerCharacter(String name, String dialogue)
        {
            this.Name = name;
            this.dialogue = dialogue;
        }

        public String Dialogue
        {
            get { return dialogue; }
            set { dialogue = value; }
        }

        public Boolean Hostile
        {
            get { return hostile; }
            set { hostile = value; }
        }
    } //end NonPlayerCharacter
} //end namespace Entity